import type { Metadata } from 'next';

import './globals.css';
import GNB from '@/components/common/GNB/pc/GNB';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GNB isLogin={false} />
        {children}
        {modal}
      </body>
    </html>
  );
}
