import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center h-screen">
        <div className="w-full grid desktop:max-w-container desktop:px-5 desktop:grid-cols-12 desktop:gap-5 noDesktop:layout">
          <div className="noDesktop:px-5">{children}</div>
        </div>
      </body>
    </html>
  );
}
