import type { Metadata } from 'next';

import './globals.css';
import GNB_PC from '@/components/common/GNB/pc/GNB';
import GNB_MOBILE from '@/components/common/GNB/mobile/GNB';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="pc:hidden mobile:block">
          <GNB_MOBILE isLogin={false} />
        </div>
        <div className="pc:block mobile:hidden">
          <GNB_PC isLogin={false} />
        </div>
        {children}
        {modal}
      </body>
    </html>
  );
}
