export interface ActivityCardItem {
  detailLink: string;
  activityType: string;
  source: string;
  title: string;
  organizer: string;
  companyType: string;
  target: string;
  registrationPeriod: string;
  activityPeriod: string;
  recruitment: string;
  region: string;
  homepage: string;
  contestField: string;
  activityField: string;
  costPrize: string;
  thumbnailImage: string;
  detailImage: string;
}

export const CardData: ActivityCardItem[] = [
  {
    detailLink: '/activity/302756',
    activityType: '대외활동',
    source: '링커리어',
    title: '[한국정책방송원(KTV 국민방송)] KTV 온라인 청년 크리에이터 모집(~2/27)',
    organizer: '한국정책방송원(KTV 국민방송)',
    companyType: '공공기관/공기업',
    target: '대학생, 직장인/일반인',
    registrationPeriod: '2026.02.12 ~ 2026.02.27',
    activityPeriod: '26.2 ~ 26.11',
    recruitment: '00명',
    region: '지역 제한없음',
    homepage: 'https://www.ktv.go.kr/',
    contestField: '',
    activityField: '서포터즈; 마케터',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766769',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766768',
  },
  {
    detailLink: '/activity/302706',
    activityType: '대외활동',
    source: '링커리어',
    title: '재외동포청 워킹홀리데이 서포터스 [워홀프렌즈 15기] 모집',
    organizer: '재외동포청 워킹홀리데이 인포센터',
    companyType: '공공기관/공기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.01.29 ~ 2026.03.02',
    activityPeriod: '26.3 ~ 26.8',
    recruitment: '20명',
    region: '지역 제한없음',
    homepage: '',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766520',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766519',
  },
  {
    detailLink: '/activity/302688',
    activityType: '대외활동',
    source: '링커리어',
    title: '[대기업 마케터 강의+실무경험] 강의, 실무경험, 성과분석까지 한 번에! 숏폼 마케팅 11주 힐링캠프',
    organizer: '대외활동플러스',
    companyType: '기타',
    target: '대학생',
    registrationPeriod: '2026.02.12 ~ 2026.02.25',
    activityPeriod: '26.2 ~ 26.6',
    recruitment: '10명',
    region: '서울 서대문구',
    homepage: 'https://blog.naver.com/aplusstory',
    contestField: '',
    activityField: '마케터; 멘토링',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766496',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766502',
  },
  {
    detailLink: '/activity/302677',
    activityType: '대외활동',
    source: '링커리어',
    title: '대한민국 대학생 교육기부단 부산경남권역본부 28기 집행부 모집',
    organizer: '대한민국 대학생 교육기부단',
    companyType: '비영리단체/협회/재단',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.08 ~ 2026.02.19',
    activityPeriod: '26.2 ~ 27.2',
    recruitment: '0명',
    region: '부산 전체, 울산 전체',
    homepage: '',
    contestField: '',
    activityField: '봉사단-국내',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766413',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766412',
  },
  {
    detailLink: '/activity/302674',
    activityType: '대외활동',
    source: '링커리어',
    title: '커리어도 쌓고 활동비 받기 가능한 현직자 멘토 모집 (1회 최대 15만원)',
    organizer: '금천구청년활동공간 청춘삘딩',
    companyType: '공공기관/공기업',
    target: '직장인/일반인',
    registrationPeriod: '2026.02.10 ~ 2026.03.02',
    activityPeriod: '26.3 ~ 26.11',
    recruitment: '00명',
    region: '서울 전체',
    homepage: '',
    contestField: '',
    activityField: '멘토링',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766400',
    detailImage: '',
  },
  {
    detailLink: '/activity/302672',
    activityType: '대외활동',
    source: '링커리어',
    title: '[고우해커스]★멘토 칼럼 후기 쓰고 SAT 자료집 5종 받자!★',
    organizer: '해커스어학원',
    companyType: '중견기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.13 ~ 2026.02.23',
    activityPeriod: '26.1 ~ 26.2',
    recruitment: '996명',
    region: '지역 제한없음',
    homepage: 'https://gouk.kr/qsWEUk',
    contestField: '',
    activityField: '기타',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766392',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766391',
  },
  {
    detailLink: '/activity/302668',
    activityType: '대외활동',
    source: '링커리어',
    title: '2026년 SYMF 페스티벌 기획단 모집',
    organizer: '시립청소년음악센터',
    companyType: '비영리단체/협회/재단',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.06 ~ 2026.02.21',
    activityPeriod: '26.2 ~ 26.12',
    recruitment: '00명',
    region: '서울',
    homepage: 'https://www.tippingkorea.co.kr/kr/quick_banner/list.php?idx=45017',
    contestField: '',
    activityField: '봉사단-국내; 서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766378',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766377',
  },
  {
    detailLink: '/activity/302661',
    activityType: '대외활동',
    source: '링커리어',
    title: '[한국마케팅협회] 제26기 트렌드마케팅 CEO 과정 II 조교모집',
    organizer: '사단법인 한국마케팅협회',
    companyType: '비영리단체/협회/재단',
    target: '대학생, 직장인/일반인',
    registrationPeriod: '2026.02.12 ~ 모집 시 마감',
    activityPeriod: '26.1 ~ 26.2',
    recruitment: '1명',
    region: '서울 전체',
    homepage: 'http://prideofkorea.com/',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766359',
    detailImage: '',
  },
  {
    detailLink: '/activity/302658',
    activityType: '대외활동',
    source: '링커리어',
    title: 'ESG 서포터즈(3기)',
    organizer: '시립중랑노인종합복지관',
    companyType: '공공기관/공기업',
    target: '대학생',
    registrationPeriod: '2026.02.12 ~ 2026.03.02',
    activityPeriod: '26.2 ~ 26.7',
    recruitment: '00명',
    region: '지역 제한없음',
    homepage: 'http://www.jnnoin.com',
    contestField: '',
    activityField: '서포터즈; 봉사단-국내',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766350',
    detailImage: '',
  },
  {
    detailLink: '/activity/302651',
    activityType: '대외활동',
    source: '링커리어',
    title: '2026년 경상북도청소년수련원 청소년운영위원회 길라잡이 제 18기 모집',
    organizer: '경상북도청소년수련원',
    companyType: '비영리단체/협회/재단',
    target: '청소년',
    registrationPeriod: '2026.02.18 ~ 2026.03.15',
    activityPeriod: '26.2 ~ 27.3',
    recruitment: '00명',
    region: '경상',
    homepage:
      'https://www.gbyc.co.kr/board/detail.tc?mn=1009&viewType=sub&mngNo=104&pageIndex=1&boardName=ANNOUNCEMENT&boardNo=5940&pageSeq=653&preview=&previewTempl=&searchCondition=0&searchKeyword=',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766315',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766313',
  },
  {
    detailLink: '/activity/302650',
    activityType: '대외활동',
    source: '링커리어',
    title: '2026년 제6기 강서영상크리에이터 모집',
    organizer: '강서구청',
    companyType: '공공기관/공기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.10 ~ 2026.03.03',
    activityPeriod: '26.2 ~ 26.12',
    recruitment: '00명',
    region: '서울 강서구',
    homepage:
      'https://www.gangseo.seoul.kr/gs040101/317591?srchCtgry=&srchStdg=&curPage=&srchKey=&srchText=&srchBeginDt=&srchEndDt=',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766311',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766310',
  },
  {
    detailLink: '/activity/302648',
    activityType: '대외활동',
    source: '링커리어',
    title: '[아시아평화를향한이주 MAP] 2026년도 상반기 자원활동가 모집',
    organizer: '아시아평화를향한이주',
    companyType: '비영리단체/협회/재단',
    target: '대학생, 직장인/일반인',
    registrationPeriod: '2026.02.12 ~ 2026.02.22',
    activityPeriod: '26.2 ~ 26.7',
    recruitment: '00명',
    region: '지역 제한없음',
    homepage: 'https://mapcast.org',
    contestField: '',
    activityField: '기타; 봉사단-국내',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766314',
    detailImage: '',
  },
  {
    detailLink: '/activity/302635',
    activityType: '대외활동',
    source: '링커리어',
    title: '2026 서울문화재단 스팍메이트 16기 모집',
    organizer: '서울문화재단',
    companyType: '공공기관/공기업',
    target: '대학생',
    registrationPeriod: '2026.02.08 ~ 2026.02.27',
    activityPeriod: '26.2 ~ 26.12',
    recruitment: '0명',
    region: '서울 전체',
    homepage: '',
    contestField: '',
    activityField: '기자단',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766402',
    detailImage: '',
  },
  {
    detailLink: '/activity/302628',
    activityType: '대외활동',
    source: '링커리어',
    title: '서울문화재단 스팍메이트 16기 모집',
    organizer: '서울문화재단',
    companyType: '비영리단체/협회/재단',
    target: '대학생',
    registrationPeriod: '2026.02.08 ~ 2026.02.27',
    activityPeriod: '26.2 ~ 26.12',
    recruitment: '0명',
    region: '서울',
    homepage: 'https://www.sfac.or.kr/participation/participation/artspace_project.do?pageIndex=1&firstPageIndex=1&lastPageIndex=&searchSttusCd=&prjIdx=301&step=1&searchSpceCode=',
    contestField: '',
    activityField: '서포터즈; 기자단',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766199',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766198',
  },
  {
    detailLink: '/activity/302623',
    activityType: '대외활동',
    source: '링커리어',
    title: 'ESG 관심 있어? 성과로 증명하는 ESG로 기획부터 실행까지, 진짜 스펙 쌓아보자!',
    organizer: '한국대학생인재협회',
    companyType: '비영리단체/협회/재단',
    target: '대학생',
    registrationPeriod: '2026.02.12 ~ 2026.02.25',
    activityPeriod: '26.2 ~ 26.6',
    recruitment: '10명',
    region: '서울 서대문구',
    homepage: 'https://blog.naver.com/aplusstory',
    contestField: '',
    activityField: '마케터; 멘토링',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766171',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766163; https://media-cdn.linkareer.com//se2editor/image/766164',
  },
  {
    detailLink: '/activity/302608',
    activityType: '대외활동',
    source: '링커리어',
    title: '[경기도의회] 2026년 SNS 서포터즈 모집 (~2/27)',
    organizer: '주식회사 생각하는늑대',
    companyType: '중소기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.12 ~ 2026.02.27',
    activityPeriod: '26.3 ~ 26.9',
    recruitment: '20명',
    region: '경기 전체',
    homepage: '',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766127',
    detailImage: '',
  },
  {
    detailLink: '/activity/302606',
    activityType: '대외활동',
    source: '링커리어',
    title: '내가 직접 만드는 포럼 ! ⭐제5기 청년플러스 서포터즈 모집⭐',
    organizer: '청년플러스포럼',
    companyType: '기타',
    target: '대학생',
    registrationPeriod: '2026.02.11 ~ 2026.03.02',
    activityPeriod: '-',
    recruitment: '00명',
    region: '지역 제한없음',
    homepage: 'https://www.ypforum.kr/',
    contestField: '',
    activityField: '서포터즈; 기자단',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766126',
    detailImage: 'https://media-cdn.linkareer.com//se2editor/image/766150',
  },
  {
    detailLink: '/activity/302603',
    activityType: '대외활동',
    source: '링커리어',
    title: '[한국교통안전공단] 교통안전 기자단 <TS 탠젤크루> 1기 모집 (~3/23)',
    organizer: '한국교통안전공단',
    companyType: '공공기관/공기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.13 ~ 2026.03.23',
    activityPeriod: '26.3 ~ 26.7',
    recruitment: '0명',
    region: '지역 제한없음',
    homepage: '',
    contestField: '',
    activityField: '서포터즈; 기자단',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766121',
    detailImage: '',
  },
  {
    detailLink: '/activity/302589',
    activityType: '대외활동',
    source: '링커리어',
    title: '[서큘러스] AI·로봇 교육 운영과 SNS 콘텐츠 제작을 직접 경험할 대학생 서포터즈 모집(~3/4)',
    organizer: '(주)서큘러스',
    companyType: '중소기업',
    target: '대학생',
    registrationPeriod: '2026.02.12 ~ 2026.03.04',
    activityPeriod: '26.2 ~ 26.8',
    recruitment: '0명',
    region: '지역 제한없음',
    homepage: 'https://circul.us/',
    contestField: '',
    activityField: '서포터즈; 마케터',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766338',
    detailImage: '',
  },
  {
    detailLink: '/activity/302586',
    activityType: '대외활동',
    source: '링커리어',
    title: '[윈스펙] 공기업 취업 서포터즈 129기 모집',
    organizer: '윈스펙',
    companyType: '중소기업',
    target: '대상 제한 없음',
    registrationPeriod: '2026.02.15 ~ 2026.02.27',
    activityPeriod: '26.2 ~ 26.3',
    recruitment: '200명',
    region: '지역 제한없음',
    homepage: 'https://www.winspec.co.kr/',
    contestField: '',
    activityField: '서포터즈',
    costPrize: '',
    thumbnailImage: 'https://api.linkareer.com/attachments/766060',
    detailImage: '',
  },
];

export const ListItemData = CardData.map((item) => ({
  title: item.title,
  organizer: item.organizer,
  registrationPeriod: item.registrationPeriod,
  activityPeriod: item.activityPeriod,
  region: item.region,
  thumbnailImage: item.thumbnailImage,
}));
